# Generated by Django 4.2 on 2025-04-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_connectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='share_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
