# Generated by Django 4.2 on 2025-04-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_event_category_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='show_in_calendar',
            field=models.BooleanField(default=True),
        ),
    ]
